"""
quantum_alice.py — Real Quantum State Preparation using Qiskit
==============================================================

Replaces the pseudo-random simulation in alice.py with REAL quantum circuits.

Key differences from alice.py
------------------------------
• alice.py  : uses numpy.random.randint  → classical pseudo-random numbers
• this file : uses Hadamard-gate circuits → TRUE quantum randomness
              (each measurement of |+⟩ = H|0⟩ is fundamentally unpredictable,
               guaranteed by quantum mechanics, not an algorithm)

BB84 photon-polarisation → quantum circuit mapping
----------------------------------------------------
  bit=0, basis=0 (+, Rectilinear) : |0⟩          — no gates
  bit=1, basis=0 (+, Rectilinear) : |1⟩          — X gate
  bit=0, basis=1 (x, Diagonal)   : |+⟩ = H|0⟩   — H gate
  bit=1, basis=1 (x, Diagonal)   : |−⟩ = HX|0⟩  — X then H

Dependencies: qiskit, qiskit-aer
"""

import warnings
from typing import List, Tuple, Optional

# ---------------------------------------------------------------------------
# Qiskit imports — wrapped so we give a clear error if not installed
# ---------------------------------------------------------------------------
try:
    from qiskit import QuantumCircuit, transpile
    from qiskit_aer import AerSimulator
    QISKIT_AVAILABLE = True
except ImportError:
    QISKIT_AVAILABLE = False
    warnings.warn(
        "Qiskit / qiskit-aer not found.  "
        "Install with: pip install qiskit qiskit-aer qiskit-ibm-runtime",
        RuntimeWarning,
        stacklevel=2,
    )


def _require_qiskit() -> None:
    """Raise a clear ImportError if Qiskit is not installed."""
    if not QISKIT_AVAILABLE:
        raise ImportError(
            "Qiskit is required but not installed.\n"
            "Run:  pip install qiskit qiskit-aer qiskit-ibm-runtime"
        )


# ===========================================================================
# QuantumAlice — real quantum state preparation
# ===========================================================================
class QuantumAlice:
    """
    Alice's quantum role in BB84, implemented with REAL quantum circuits.

    Uses Qiskit to build one-qubit circuits that physically represent the
    four BB84 polarisation states. Randomness is generated by measuring
    qubits in the |+⟩ superposition — true quantum randomness.

    Attributes
    ----------
    num_qubits        : int             Total qubits to prepare.
    use_real_hardware : bool            True → IBM Quantum, False → AerSimulator.
    backend           : AerSimulator    The local or remote Qiskit backend.
    bits              : list[int]       Alice's randomly generated bits.
    bases             : list[int]       Alice's randomly generated bases.
    circuits          : list[QuantumCircuit]  One state-prep circuit per qubit.
    """

    # -----------------------------------------------------------------------
    def __init__(
        self,
        num_qubits: int,
        use_real_hardware: bool = False,
        ibm_token: Optional[str] = None,
    ):
        """
        Initialise QuantumAlice.

        Parameters
        ----------
        num_qubits        : Number of photons (qubits) Alice will prepare.
        use_real_hardware : If True, attempt to connect to IBM Quantum.
        ibm_token         : IBM Quantum API token (only needed for real HW).
                            If None but use_real_hardware=True, falls back
                            to AerSimulator with a warning.
        """
        _require_qiskit()

        self.num_qubits        = num_qubits
        self.use_real_hardware = use_real_hardware
        self.bits:    List[int]            = []
        self.bases:   List[int]            = []
        self.circuits: List[QuantumCircuit] = []

        # ---- Initialise backend --------------------------------------------
        if use_real_hardware and ibm_token:
            self.backend = self._connect_ibm(ibm_token)
        else:
            if use_real_hardware and not ibm_token:
                warnings.warn(
                    "use_real_hardware=True but no ibm_token provided. "
                    "Falling back to AerSimulator (local simulation).",
                    UserWarning,
                    stacklevel=2,
                )
            # Default: fast local quantum simulator
            self.backend = AerSimulator()
            print("✓ Backend initialised: Qiskit AerSimulator (local quantum simulation)")

    # -----------------------------------------------------------------------
    def _connect_ibm(self, token: str):
        """
        Connect to IBM Quantum and return the least-busy backend.

        Falls back to AerSimulator if the connection fails or the
        qiskit-ibm-runtime package is missing.

        Parameters
        ----------
        token : IBM Quantum API token from https://quantum.ibm.com

        Returns
        -------
        Backend suitable for submitting circuits.
        """
        try:
            from qiskit_ibm_runtime import QiskitRuntimeService
            print("Connecting to IBM Quantum...")
            service = QiskitRuntimeService(channel="ibm_quantum", token=token)
            # Pick the least congested real device with >= 5 qubits
            backend = service.least_busy(operational=True, simulator=False, min_num_qubits=5)
            print(f"✓ Connected to IBM Quantum hardware: {backend.name}")
            return backend
        except Exception as exc:
            warnings.warn(
                f"IBM Quantum connection failed ({exc}). "
                "Falling back to AerSimulator.",
                UserWarning,
                stacklevel=3,
            )
            self.use_real_hardware = False
            return AerSimulator()

    # -----------------------------------------------------------------------
    # Core quantum helper — measure a batched set of H-gate qubits for randomness
    # -----------------------------------------------------------------------
    def _quantum_random_bits(self, n: int) -> List[int]:
        """
        Generate n truly-random bits using batched quantum circuits.

        AerSimulator's default coupling map caps single circuits at 30 qubits.
        We work around this by chunking into batches of up to 30 qubits,
        running each batch separately, and concatenating the results.
        Each qubit goes through H+measure — genuine quantum randomness.

        Parameters
        ----------
        n : Number of random bits to generate.

        Returns
        -------
        list[int] : n bits, each 0 or 1.
        """
        MAX_QUBITS_PER_CIRCUIT = 29  # stay below AerSimulator coupling-map limit
        bits: List[int] = []

        remaining = n
        while remaining > 0:
            chunk = min(remaining, MAX_QUBITS_PER_CIRCUIT)

            qc = QuantumCircuit(chunk, chunk)
            for i in range(chunk):
                qc.h(i)
            qc.measure(list(range(chunk)), list(range(chunk)))

            compiled   = transpile(qc, self.backend)
            job        = self.backend.run(compiled, shots=1)
            result_str = list(job.result().get_counts().keys())[0]

            # Qiskit: qubit 0 is the RIGHTMOST character — reverse so index 0 = qubit 0
            chunk_bits = [int(b) for b in reversed(result_str)]
            bits.extend(chunk_bits[:chunk])
            remaining -= chunk

        return bits[:n]

    # -----------------------------------------------------------------------
    # PUBLIC API
    # -----------------------------------------------------------------------

    def prepare_qubit_circuit(self, bit: int, basis: int) -> QuantumCircuit:
        """
        Create a REAL quantum circuit encoding one BB84 photon state.

        The circuit starts with |0⟩ and applies gates to produce the
        correct polarisation state for the given bit/basis combination.
        No measurement is added here — Bob will add his own measurement
        gate later when he chooses his basis.

        BB84 encoding table
        -------------------
        bit=0, basis=0 -> |0> (no gates)         horizontal   0 deg
        bit=1, basis=0 -> |1> (X gate)           vertical    90 deg
        bit=0, basis=1 -> |+> (H gate)           diagonal    45 deg
        bit=1, basis=1 -> |-> (X then H gate)    diagonal   135 deg

        Parameters
        ----------
        bit   : 0 or 1 — the classical bit Alice wants to encode.
        basis : 0 (+, rectilinear) or 1 (x, diagonal).

        Returns
        -------
        QuantumCircuit(1, 1) with the state-preparation gates applied.
                             Measurement NOT included (Bob adds it).
        """
        qc = QuantumCircuit(1, 1)

        if basis == 0:
            # Rectilinear basis (+):  0 deg or 90 deg polarisation
            if bit == 1:
                qc.x(0)          # |0> -> |1>  (vertical, 90 deg)
            # else: |0> stays as-is  (horizontal, 0 deg)

        else:
            # Diagonal basis (x):  45 deg or 135 deg polarisation
            if bit == 1:
                qc.x(0)          # |0> -> |1> first, then...
            qc.h(0)              # H maps:  |0> -> |+> (45 deg), |1> -> |-> (135 deg)

        return qc

    # -----------------------------------------------------------------------
    def generate_key_circuits(
        self, bits: List[int], bases: List[int]
    ) -> List[QuantumCircuit]:
        """
        Build a quantum circuit for each qubit in the BB84 stream.

        Parameters
        ----------
        bits  : Alice's bit values (0 or 1), one per qubit.
        bases : Alice's basis choices (0 or 1), one per qubit.

        Returns
        -------
        list[QuantumCircuit] — one state-prep circuit per qubit, in order.
        """
        if len(bits) != len(bases):
            raise ValueError(
                f"bits length ({len(bits)}) != bases length ({len(bases)})"
            )

        circuits = [
            self.prepare_qubit_circuit(b, ba)
            for b, ba in zip(bits, bases)
        ]

        n = len(circuits)
        print(f"✓ Prepared {n} quantum circuits using real quantum gates")
        return circuits

    # -----------------------------------------------------------------------
    def encode_all(self, num_qubits: Optional[int] = None) -> Tuple[
        List[int], List[int], List[QuantumCircuit]
    ]:
        """
        Full Alice encoding pipeline using quantum randomness throughout.

        Steps
        -----
        1. Generate num_qubits truly random bits (H+measure on each qubit).
        2. Generate num_qubits truly random bases the same way.
        3. Build one state-prep circuit per qubit.

        Parameters
        ----------
        num_qubits : Override self.num_qubits if provided.

        Returns
        -------
        bits     : list[int]          — Alice's quantum-random bits.
        bases    : list[int]          — Alice's quantum-random bases.
        circuits : list[QuantumCircuit] — State-prep circuit per qubit.
        """
        n = num_qubits if num_qubits is not None else self.num_qubits

        # ---- Step 1: Quantum-random bits -----------------------------------
        print(f"\n[Alice] Generating {n} quantum-random bits (H-gate measurement)...")
        self.bits = self._quantum_random_bits(n)
        print(f"  -> Bits  (first 16): {self.bits[:16]}{'...' if n > 16 else ''}")

        # ---- Step 2: Quantum-random bases ----------------------------------
        print(f"[Alice] Generating {n} quantum-random bases (H-gate measurement)...")
        self.bases = self._quantum_random_bits(n)
        print(f"  -> Bases (first 16): {self.bases[:16]}{'...' if n > 16 else ''}")

        # ---- Step 3: Build state-prep circuits ----------------------------
        print(f"[Alice] Building {n} BB84 state-preparation circuits...")
        self.circuits = self.generate_key_circuits(self.bits, self.bases)

        return self.bits, self.bases, self.circuits

    # -----------------------------------------------------------------------
    def print_quantum_info(self, num_show: int = 3) -> None:
        """
        Print the text diagram of the first `num_show` qubit circuits.

        Useful for verifying the circuit structure and understanding how
        each BB84 state is physically prepared.

        Parameters
        ----------
        num_show : Number of circuits to display (default: 3).
        """
        if not self.circuits:
            print("[Alice] No circuits generated yet. Call encode_all() first.")
            return

        _basis_name = {0: "Rectilinear (+)", 1: "Diagonal (x)"}
        _state_label = {
            (0, 0): "|0> -- horizontal   0 deg",
            (1, 0): "|1> -- vertical    90 deg",
            (0, 1): "|+> -- diagonal    45 deg",
            (1, 1): "|-> -- diagonal   135 deg",
        }

        limit = min(num_show, len(self.circuits))
        print(f"\n{'='*55}")
        print(f"  Alice's Quantum Circuits (first {limit} of {len(self.circuits)})")
        print(f"{'='*55}")

        for i in range(limit):
            bit   = self.bits[i]
            basis = self.bases[i]
            label = _state_label.get((bit, basis), "unknown")
            print(f"\nQubit {i}  |  bit={bit}, basis={_basis_name[basis]}")
            print(f"Target state: {label}")
            print(self.circuits[i].draw("text"))

        print(f"{'='*55}\n")

    # -----------------------------------------------------------------------
    def get_backend_info(self) -> str:
        """Return a human-readable string describing the active backend."""
        if self.use_real_hardware:
            return f"IBM Quantum Hardware: {self.backend.name}"
        return "Qiskit AerSimulator (local quantum simulation -- free, fast, unlimited)"


# ===========================================================================
# Standalone test
# ===========================================================================
if __name__ == "__main__":
    print("=" * 60)
    print("  quantum_alice.py -- standalone test")
    print("  Using Qiskit AerSimulator (local)")
    print("=" * 60)

    NUM_QUBITS = 16

    alice = QuantumAlice(num_qubits=NUM_QUBITS)
    print(f"\nBackend: {alice.get_backend_info()}\n")

    bits, bases, circuits = alice.encode_all(NUM_QUBITS)

    alice.print_quantum_info(num_show=3)

    print(f"Alice bits  : {bits}")
    print(f"Alice bases : {bases}")
    print(f"Circuits    : {len(circuits)} circuits generated")
    print("\n✅ quantum_alice.py test complete")
